### ISSUE TITLE
Admin-Paid for inspection -assigned supervisor

### ISSUE THREAD

**Issue by NimeshaShehani** [Vithana94/FireCertificate#10]
- [x] try to give date range for **_inspection date._**
![image](https://github.com/Vithana94/FireCertificate/assets/99183446/f606791d-232d-4218-93ae-69297c6e3dbb)

- [x] Here back button must be redirected to paid for inspection overview.
![image](https://github.com/Vithana94/FireCertificate/assets/99183446/cb392235-a88d-477f-afa6-12a3ab9ae6b5)

**Comment by DeshaniNekfa** [comment]
Fixed
