### ISSUE TITLE
Admin- Issued, Hold and Reject Overview (FC116)

### ISSUE THREAD

**Issue by NimeshaShehani** [Vithana94/FireCertificate#27]
- [ ] Correct issued date, hold and reject date.

![image](https://github.com/Vithana94/FireCertificate/assets/99183446/7c775ed6-08c1-4df9-8279-615c143999c2)
![image](https://github.com/Vithana94/FireCertificate/assets/99183446/d020601f-2ba8-483c-b302-13498223a386)

**Comment by Vithana94** [comment]
c448b4846618839ddebd27ba73f058e4c63a875b
